

frase ='   Curso em video Python   '
print(frase[1:13:2])
print()
print(frase.upper().count('O'))
print()
print(frase.upper())
print()
print(len(frase))
print()
print(len(frase.strip()))
print()
print(frase.strip())
print()
print(frase.split())
print()
frase_dividida = frase.split()
print(frase_dividida)
print(frase_dividida[0])
print(frase_dividida[1])
print(frase_dividida[2])
print(frase_dividida[3])
print()
print(frase_dividida[3][2])
print()
print(frase.replace('Python', 'Android'))
print()
print(frase)
print()
frase2 = frase.replace('Python', 'Android')
print(frase2)
print()
print('Curso' in frase)
print()
print(frase.find('video'))
print()
print(frase.find('Video'))
print()
print()
print("""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint""")


